export const users = [
  {
    name: "Yosip Mike Colin",
    nit: "83749234",
    perfil: "Requiriente",
    status: "Activo",
    email: "yosipmikecolin@example.com",
    creation_date: "2022-03-15",
    phone: "310 123 4567",
  },
  {
    name: "Andres Alfonso",
    nit: "5937450378",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "andresalfonso@example.com",
    creation_date: "2021-07-22",
    phone: "320 234 5678",
  },
  {
    name: "Maria Salazar",
    nit: "5905645028",
    perfil: "Administrador",
    status: "Activo",
    email: "mariasalazar@example.com",
    creation_date: "2023-01-10",
    phone: "300 345 6789",
  },
  {
    name: "Luciana Gómez",
    nit: "4538294850",
    perfil: "Requiriente",
    status: "Activo",
    email: "lucianagomez@example.com",
    creation_date: "2022-11-05",
    phone: "315 456 7890",
  },
  {
    name: "Carlos Pérez",
    nit: "5893247324",
    perfil: "Administrador",
    status: "Inactivo",
    email: "carlosperez@example.com",
    creation_date: "2021-09-30",
    phone: "318 567 8901",
  },
  {
    name: "Laura Martínez",
    nit: "4823952345",
    perfil: "Requiriente",
    status: "Activo",
    email: "lauramartinez@example.com",
    creation_date: "2023-04-12",
    phone: "311 678 9012",
  },
  {
    name: "Jorge Fernández",
    nit: "7583940238",
    perfil: "Coordinador",
    status: "Activo",
    email: "jorgefernandez@example.com",
    creation_date: "2022-08-19",
    phone: "313 789 0123",
  },
  {
    name: "Andrea Torres",
    nit: "9384752384",
    perfil: "Administrador",
    status: "Activo",
    email: "andreatorres@example.com",
    creation_date: "2021-12-25",
    phone: "314 890 1234",
  },
  {
    name: "Camila Ruiz",
    nit: "8364928472",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "camilaruiz@example.com",
    creation_date: "2023-02-14",
    phone: "317 901 2345",
  },
  {
    name: "Felipe Mejía",
    nit: "2394853205",
    perfil: "Coordinador",
    status: "Activo",
    email: "felipemejia@example.com",
    creation_date: "2022-05-20",
    phone: "319 012 3456",
  },
  {
    name: "Paola Herrera",
    nit: "7382947583",
    perfil: "Requiriente",
    status: "Activo",
    email: "paolaherrera@example.com",
    creation_date: "2021-10-08",
    phone: "312 123 4567",
  },
  {
    name: "Sebastián Vega",
    nit: "5932840239",
    perfil: "Requiriente",
    status: "Inactivo",
    email: "sebastianvega@example.com",
    creation_date: "2023-03-01",
    phone: "316 234 5678",
  },
  {
    name: "Natalia Castro",
    nit: "8402938472",
    perfil: "Administrador",
    status: "Activo",
    email: "nataliacastro@example.com",
    creation_date: "2022-06-18",
    phone: "310 345 6789",
  },
  {
    name: "Fernando Morales",
    nit: "7562937482",
    perfil: "Coordinador",
    status: "Inactivo",
    email: "fernandomorales@example.com",
    creation_date: "2021-11-11",
    phone: "320 456 7890",
  },
  {
    name: "Sofia Rojas",
    nit: "2938745029",
    perfil: "Requiriente",
    status: "Activo",
    email: "sofiarojas@example.com",
    creation_date: "2023-05-09",
    phone: "300 567 8901",
  },
];
export const carriers = [
  {
    personalData: {
      fullName: "Ana María Gómez Pérez",
      socialName: "Anita",
      paternalSurname: "Gómez",
      motherSurname: "Pérez",
      type_current: "Persona en libertad condicional",
      gender: "Femenino",
      dateBirth: "1990-03-10",
      maritalStatus: "Casado/a",
      nationality: "Colombia",
      run: "9876543-2",
      phone: "+57 311 987 6543",
      foreigner: false,
    },
    cause: {
      penatype: "Libertad condicional",
      crime: "Hurto agravado",
      courtAppeals: "Sin apelaciones",
      courtRegion: "Metropolitana",
      court: "Juzgado Penal de Bogotá",
      ruc: "987654321",
      rit: "123456789",
      rol: "ROL98765",
    },
    monitoring: {
      crs: "CRS Centro",
      areas: "Zona Residencial",
      durationMeasurement: "3 años",
      controlSchedule: "Martes y Jueves, 10:00 - 16:00",
      effectivePeriod: "2 años",
      requestsFeasibility: "Factibilidad en evaluación",
      judgment: "Sentencia firme",
      programmingInstallation: "Pendiente",
      installationsDone: "No",
      modificationResolution: "Sin modificaciones",
      technicalSupports: "Ninguno",
      nonReports: "Sin reportes",
      daysControl: "0",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Calle Falsa",
      number: "123",
      additionalInformation: "Apartamento 4B",
      commune: "Chapinero",
      region: "Bogotá",
      road: "Vía principal",
      population: "Urbana",
      zipCode: "110221",
      geographicCoordinates: "4.653, -74.056",
      radio: "Radio de 500 metros",
      complianceSchedule: "Cumplimiento semanal",
      characteristics: "Residencia unifamiliar",
    },
    exclusionArea: {
      street: "Avenida Siempre Viva",
      number: "742",
      additionalInformation: "Casa amarilla",
      commune: "Teusaquillo",
      region: "Bogotá",
      road: "Avenida",
      population: "Urbana",
      zipCode: "111311",
      geographicCoordinates: "4.635, -74.080",
      radio: "Radio de 300 metros",
      characteristics: "Casa esquinera",
      paternalSurname: "López",
      motherSurname: "Díaz",
      names: "Carlos Alberto",
      rut: "8765432-1",
      victimEmail: "victima@correo.com",
      homeTelephone: "+57 1 555 1212",
      workplaceTelephone: "+57 1 555 3434",
    },
  },
  {
    personalData: {
      fullName: "Pedro Luis Rodríguez Castro",
      socialName: "Pedrito",
      paternalSurname: "Rodríguez",
      motherSurname: "Castro",
      type_current: "Persona con arresto domiciliario",
      gender: "Masculino",
      dateBirth: "1978-11-22",
      maritalStatus: "Divorciado/a",
      nationality: "Venezuela",
      run: "V-12345678",
      phone: "+57 320 112 2334",
      foreigner: true,
    },
    cause: {
      penatype: "Arresto domiciliario",
      crime: "Lesiones personales",
      courtAppeals: "Apelación en curso",
      courtRegion: "Valparaíso",
      court: "Juzgado de Familia de Bogotá",
      ruc: "098765432",
      rit: "234567890",
      rol: "ROL09876",
    },
    monitoring: {
      crs: "CRS Occidente",
      areas: "Periferia",
      durationMeasurement: "1 año",
      controlSchedule: "Lunes, Miércoles y Viernes, 14:00 - 18:00",
      effectivePeriod: "6 meses",
      requestsFeasibility: "Factibilidad técnica aprobada",
      judgment: "Sentencia de primera instancia",
      programmingInstallation: "Completada",
      installationsDone: "Sí, 2024-07-01",
      modificationResolution: "Resolución de ampliación",
      technicalSupports: "Soporte remoto 2024-08-15",
      nonReports: "Un reporte el 2024-09-01",
      daysControl: "150",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Carrera Inexistente",
      number: "S/N",
      additionalInformation: "Finca La Esperanza",
      commune: "Usme",
      region: "Bogotá",
      road: "Carretera",
      population: "Rural",
      zipCode: "110851",
      geographicCoordinates: "4.550, -74.100",
      radio: "Radio de 1000 metros",
      complianceSchedule: "Cumplimiento mensual",
      characteristics: "Finca con amplias zonas verdes",
    },
    exclusionArea: {
      street: "Diagonal Olvidada",
      number: "55-55",
      additionalInformation: "Local comercial",
      commune: "Kennedy",
      region: "Bogotá",
      road: "Diagonal",
      population: "Urbana",
      zipCode: "110881",
      geographicCoordinates: "4.660, -74.150",
      radio: "Radio de 200 metros",
      characteristics: "Local a pie de calle",
      paternalSurname: "Sánchez",
      motherSurname: "Ruiz",
      names: "Laura Sofía",
      rut: "10987654-3",
      victimEmail: "damnificada@otrocorreo.net",
      homeTelephone: "+57 1 666 7878",
      workplaceTelephone: "+57 1 666 9090",
    },
  },
  {
    personalData: {
      fullName: "Sofía Elena Vargas López",
      socialName: "Sofi",
      paternalSurname: "Vargas",
      motherSurname: "López",
      type_current: "Persona con medida de protección",
      gender: "Femenino",
      dateBirth: "2001-07-04",
      maritalStatus: "Soltero/a",
      nationality: "Colombia",
      run: "10111213-4",
      phone: "+57 315 223 3445",
      foreigner: false,
    },
    cause: {
      penatype: "Medida de protección",
      crime: "Violencia intrafamiliar",
      courtAppeals: "Sin apelaciones pendientes",
      courtRegion: "Biobío",
      court: "Juzgado Civil Municipal de Bogotá",
      ruc: "345678901",
      rit: "012345678",
      rol: "ROL34567",
    },
    monitoring: {
      crs: "CRS Sur",
      areas: "Zona escolar",
      durationMeasurement: "6 meses",
      controlSchedule: "Lunes a Viernes, 7:00 - 9:00 y 16:00 - 18:00",
      effectivePeriod: "4 meses",
      requestsFeasibility: "Factibilidad técnica en curso",
      judgment: "Medida cautelar",
      programmingInstallation: "En planificación",
      installationsDone: "No",
      modificationResolution: "Sin modificaciones",
      technicalSupports: "Pendiente",
      nonReports: "Sin reportes",
      daysControl: "0",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Transversal Imaginaria",
      number: "456",
      additionalInformation: "Cerca al parque",
      commune: "Ciudad Bolívar",
      region: "Bogotá",
      road: "Transversal",
      population: "Urbana",
      zipCode: "111931",
      geographicCoordinates: "4.580, -74.180",
      radio: "Radio de 400 metros",
      complianceSchedule: "Cumplimiento diario",
      characteristics: "Casa de dos pisos",
    },
    exclusionArea: {
      street: "Calle del Recuerdo",
      number: "987",
      additionalInformation: "Edificio azul",
      commune: "Bosa",
      region: "Bogotá",
      road: "Calle",
      population: "Urbana",
      zipCode: "110711",
      geographicCoordinates: "4.680, -74.200",
      radio: "Radio de 150 metros",
      characteristics: "Apartamento en tercer piso",
      paternalSurname: "Martínez",
      motherSurname: "Suárez",
      names: "Javier Andrés",
      rut: "11223344-5",
      victimEmail: "protegida@email.org",
      homeTelephone: "+57 1 777 1122",
      workplaceTelephone: "N/A",
    },
  },
  {
    personalData: {
      fullName: "Ricardo Andrés Díaz Rojas",
      socialName: "Richi",
      paternalSurname: "Díaz",
      motherSurname: "Rojas",
      type_current: "Persona con suspensión condicional de la pena",
      gender: "Masculino",
      dateBirth: "1988-09-18",
      maritalStatus: "Unión libre",
      nationality: "Ecuador",
      run: "E-01234567",
      phone: "+57 318 334 4556",
      foreigner: true,
    },
    cause: {
      penatype: "Suspensión condicional",
      crime: "Conducción bajo los efectos del alcohol",
      courtAppeals: "Recurso de casación",
      courtRegion: "Villanueva",
      court: "Juzgado de Tránsito de Bogotá",
      ruc: "456789012",
      rit: "987654320",
      rol: "ROL45678",
    },
    monitoring: {
      crs: "CRS Oriente",
      areas: "Vía pública",
      durationMeasurement: "2 años",
      controlSchedule: "Sábados y Domingos, 9:00 - 12:00 y 19:00 - 21:00",
      effectivePeriod: "1 año y medio",
      requestsFeasibility: "Factibilidad técnica aprobada",
      judgment: "Sentencia en firme",
      programmingInstallation: "Completada",
      installationsDone: "Sí, 2023-11-01",
      modificationResolution: "Sin modificaciones",
      technicalSupports: "Soporte telefónico 2024-01-10",
      nonReports: "Sin reportes",
      daysControl: "450",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Avenida del Futuro",
      number: "678",
      additionalInformation: "Local 1A",
      commune: "Suba",
      region: "Bogotá",
      road: "Avenida",
      population: "Urbana",
      zipCode: "111111",
      geographicCoordinates: "4.700, -74.030",
      radio: "Radio de 350 metros",
      complianceSchedule: "Cumplimiento semanal",
      characteristics: "Edificio comercial",
    },
    exclusionArea: {
      street: "Carrera Soñada",
      number: "101",
      additionalInformation: "Oficina 202",
      commune: "Usaquén",
      region: "Bogotá",
      road: "Carrera",
      population: "Urbana",
      zipCode: "110111",
      geographicCoordinates: "4.690, -74.040",
      radio: "Radio de 250 metros",
      characteristics: "Edificio de oficinas",
      paternalSurname: "Fernández",
      motherSurname: "Guzmán",
      names: "Daniel Esteban",
      rut: "12345678-0",
      victimEmail: "afectado@mail.com",
      homeTelephone: "+57 1 888 2233",
      workplaceTelephone: "+57 1 888 4455",
    },
  },
  {
    personalData: {
      fullName: "Juan Carlos Méndez Rojas",
      socialName: "Juanquis",
      paternalSurname: "Méndez",
      motherSurname: "Rojas",
      type_current: "Persona con arresto domiciliario",
      gender: "Masculino",
      dateBirth: "1985-07-15",
      maritalStatus: "Soltero/a",
      nationality: "Chile",
      run: "12345678-9",
      phone: "+56 9 8765 4321",
      foreigner: false,
    },
    cause: {
      penatype: "Arresto domiciliario total",
      crime: "Fraude financiero",
      courtAppeals: "Corte de Apelaciones de Santiago",
      courtRegion: "Armenia",
      court: "Juzgado de Garantía de Santiago",
      ruc: "555666777",
      rit: "888999000",
      rol: "ROL54321",
    },
    monitoring: {
      crs: "CRS Norte",
      areas: "Zona Comercial",
      durationMeasurement: "18 meses",
      controlSchedule: "Lunes a Viernes, 9:00 - 18:00",
      effectivePeriod: "12 meses",
      requestsFeasibility: "Aprobada",
      judgment: "En apelación",
      programmingInstallation: "Completado",
      installationsDone: "Sí",
      modificationResolution: "Modificación aprobada",
      technicalSupports: "Brazalete electrónico",
      nonReports: "1 reporte",
      daysControl: "45",
      uninstallations: "No",
    },
    inclusionArea: {
      street: "Av. Libertador Bernardo O'Higgins",
      number: "2200",
      additionalInformation: "Departamento 1202",
      commune: "Santiago Centro",
      region: "Región Metropolitana",
      road: "Avenida principal",
      population: "Urbana",
      zipCode: "8320000",
      geographicCoordinates: "-33.456, -70.654",
      radio: "Radio de 200 metros",
      complianceSchedule: "Cumplimiento diario",
      characteristics: "Edificio residencial",
    },
    exclusionArea: {
      street: "Calle Los Placeres",
      number: "350",
      additionalInformation: "Oficina 502",
      commune: "Providencia",
      region: "Región Metropolitana",
      road: "Calle secundaria",
      population: "Urbana",
      zipCode: "7500000",
      geographicCoordinates: "-33.432, -70.623",
      radio: "Radio de 100 metros",
      characteristics: "Edificio de oficinas",
      paternalSurname: "González",
      motherSurname: "Silva",
      names: "María Fernanda",
      rut: "11222333-4",
      victimEmail: "victima1@correo.cl",
      homeTelephone: "+56 2 2345 6789",
      workplaceTelephone: "+56 2 2987 6543",
    },
  },
  {
    personalData: {
      fullName: "Laura Beatriz Sánchez Vega",
      socialName: "Lau",
      paternalSurname: "Sánchez",
      motherSurname: "Vega",
      type_current: "Persona con libertad vigilada",
      gender: "Femenino",
      dateBirth: "1992-11-25",
      maritalStatus: "Divorciado/a",
      nationality: "Argentina",
      run: "55444333-2",
      phone: "+54 9 11 7654 3210",
      foreigner: true,
    },
    cause: {
      penatype: "Libertad vigilada",
      crime: "Estafa",
      courtAppeals: "Cámara Nacional de Apelaciones",
      courtRegion: "Santander",
      court: "Juzgado Nacional en lo Criminal y Correccional N°5",
      ruc: "111222333",
      rit: "444555666",
      rol: "ROL12345",
    },
    monitoring: {
      crs: "CRS Sur",
      areas: "Zona Mixta",
      durationMeasurement: "2 años",
      controlSchedule: "Miércoles y Viernes, 14:00 - 20:00",
      effectivePeriod: "18 meses",
      requestsFeasibility: "Rechazada",
      judgment: "Firme",
      programmingInstallation: "En proceso",
      installationsDone: "Parcialmente",
      modificationResolution: "En revisión",
      technicalSupports: "Aplicación móvil",
      nonReports: "3 reportes",
      daysControl: "120",
      uninstallations: "Sí",
    },
    inclusionArea: {
      street: "Calle Florida",
      number: "800",
      additionalInformation: "Piso 3",
      commune: "Microcentro",
      region: "Buenos Aires",
      road: "Calle peatonal",
      population: "Urbana",
      zipCode: "C1005",
      geographicCoordinates: "-34.603, -58.381",
      radio: "Radio de 400 metros",
      complianceSchedule: "Cumplimiento quincenal",
      characteristics: "Edificio histórico",
    },
    exclusionArea: {
      street: "Av. Corrientes",
      number: "3200",
      additionalInformation: "Local 42",
      commune: "Balvanera",
      region: "Buenos Aires",
      road: "Avenida principal",
      population: "Urbana",
      zipCode: "C1193",
      geographicCoordinates: "-34.610, -58.411",
      radio: "Radio de 250 metros",
      characteristics: "Galpón industrial",
      paternalSurname: "Martínez",
      motherSurname: "Pérez",
      names: "Roberto Carlos",
      rut: "22333444-5",
      victimEmail: "victima2@correo.ar",
      homeTelephone: "+54 11 4789 0123",
      workplaceTelephone: "+54 11 5012 3456",
    },
  },
  {
    personalData: {
      fullName: "Pedro Antonio Ramírez Castillo",
      socialName: "",
      paternalSurname: "Ramírez",
      motherSurname: "Castillo",
      type_current: "Persona con régimen de semi-libertad",
      gender: "Masculino",
      dateBirth: "1978-05-30",
      maritalStatus: "Viudo/a",
      nationality: "Perú",
      run: "99888777-6",
      phone: "+51 987 654 321",
      foreigner: true,
    },
    cause: {
      penatype: "Semi-libertad",
      crime: "Robo con violencia",
      courtAppeals: "Corte Superior de Justicia de Lima",
      courtRegion: "Metropolitana",
      court: "Juzgado Penal de Lima",
      ruc: "777888999",
      rit: "111000222",
      rol: "ROL67890",
    },
    monitoring: {
      crs: "CRS Este",
      areas: "Zona Industrial",
      durationMeasurement: "5 años",
      controlSchedule: "Lunes, Miércoles y Viernes, 8:00 - 12:00",
      effectivePeriod: "3 años",
      requestsFeasibility: "Pendiente de revisión",
      judgment: "En ejecución",
      programmingInstallation: "Programado",
      installationsDone: "No",
      modificationResolution: "Aprobada parcialmente",
      technicalSupports: "Vigilancia activa",
      nonReports: "Sin reportes",
      daysControl: "200",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Jr. de la Unión",
      number: "1500",
      additionalInformation: "Casa verde",
      commune: "Cercado de Lima",
      region: "Lima",
      road: "Calle principal",
      population: "Urbana",
      zipCode: "15001",
      geographicCoordinates: "-12.046, -77.030",
      radio: "Radio de 350 metros",
      complianceSchedule: "Cumplimiento mensual",
      characteristics: "Vivienda unifamiliar",
    },
    exclusionArea: {
      street: "Av. Arequipa",
      number: "2500",
      additionalInformation: "Oficina 301",
      commune: "Lince",
      region: "Lima",
      road: "Avenida secundaria",
      population: "Urbana",
      zipCode: "15046",
      geographicCoordinates: "-12.075, -77.042",
      radio: "Radio de 150 metros",
      characteristics: "Edificio corporativo",
      paternalSurname: "Díaz",
      motherSurname: "Gutiérrez",
      names: "Susana Marcela",
      rut: "44555666-7",
      victimEmail: "victima3@correo.pe",
      homeTelephone: "+51 1 234 5678",
      workplaceTelephone: "+51 1 345 6789",
    },
  },
  {
    personalData: {
      fullName: "Diego Alejandro Torres Mendoza",
      socialName: "Diegito",
      paternalSurname: "Torres",
      motherSurname: "Mendoza",
      type_current: "Persona con monitorización electrónica",
      gender: "Masculino",
      dateBirth: "1988-09-12",
      maritalStatus: "Soltero/a",
      nationality: "Ecuador",
      run: "11223344-5",
      phone: "+593 99 123 4567",
      foreigner: false,
    },
    cause: {
      penatype: "Prisión domiciliaria electrónica",
      crime: "Evasión tributaria",
      courtAppeals: "Corte Provincial de Justicia",
      courtRegion: "Valparaíso",
      court: "Juzgado Segundo de Garantías Penales",
      ruc: "334455667",
      rit: "778899001",
      rol: "ROL11223",
    },
    monitoring: {
      crs: "CRS Occidental",
      areas: "Zona Rural",
      durationMeasurement: "4 años",
      controlSchedule: "Todos los días, 6:00 - 22:00",
      effectivePeriod: "3 años",
      requestsFeasibility: "Aprobada con condiciones",
      judgment: "Firme",
      programmingInstallation: "Completado",
      installationsDone: "Sí",
      modificationResolution: "Sin modificaciones",
      technicalSupports: "Brazalete GPS",
      nonReports: "2 reportes",
      daysControl: "320",
      uninstallations: "No",
    },
    inclusionArea: {
      street: "Calle de los Almendros",
      number: "45",
      additionalInformation: "Casa al fondo",
      commune: "Valle de los Chillos",
      region: "Quito",
      road: "Camino vecinal",
      population: "Rural",
      zipCode: "170135",
      geographicCoordinates: "-0.306, -78.445",
      radio: "Radio de 1 km",
      complianceSchedule: "Control permanente",
      characteristics: "Hacienda agrícola",
    },
    exclusionArea: {
      street: "Av. Amazonas",
      number: "1234",
      additionalInformation: "Edificio Financiero, piso 8",
      commune: "Centro Financiero",
      region: "Quito",
      road: "Avenida principal",
      population: "Urbana",
      zipCode: "170150",
      geographicCoordinates: "-0.218, -78.512",
      radio: "Radio de 500 metros",
      characteristics: "Edificio de oficinas bancarias",
      paternalSurname: "Vargas",
      motherSurname: "Castro",
      names: "Lucía Gabriela",
      rut: "99887766-1",
      victimEmail: "victima4@correo.ec",
      homeTelephone: "+593 2 234 5678",
      workplaceTelephone: "+593 2 345 6789",
    },
  },
  {
    personalData: {
      fullName: "Valentina Sofía Ríos Contreras",
      socialName: "Vale",
      paternalSurname: "Ríos",
      motherSurname: "Contreras",
      type_current: "Persona con régimen de salidas controladas",
      gender: "Femenino",
      dateBirth: "1995-02-28",
      maritalStatus: "Soltero/a",
      nationality: "Uruguay",
      run: "55667788-9",
      phone: "+598 98 765 432",
      foreigner: true,
    },
    cause: {
      penatype: "Salidas terapéuticas",
      crime: "Posesión de sustancias",
      courtAppeals: "Tribunal de Apelaciones",
      courtRegion: "Biobío",
      court: "Juzgado Letrado de Primera Instancia",
      ruc: "445566778",
      rit: "889900112",
      rol: "ROL44556",
    },
    monitoring: {
      crs: "CRS Oriental",
      areas: "Zona Hospitalaria",
      durationMeasurement: "1 año",
      controlSchedule: "Lunes y Jueves, 9:00 - 12:00",
      effectivePeriod: "8 meses",
      requestsFeasibility: "Aprobada",
      judgment: "En revisión",
      programmingInstallation: "No requerido",
      installationsDone: "No aplica",
      modificationResolution: "Modificación temporal",
      technicalSupports: "Supervisión presencial",
      nonReports: "Sin reportes",
      daysControl: "90",
      uninstallations: "No aplica",
    },
    inclusionArea: {
      street: "Bulevar Artigas",
      number: "2020",
      additionalInformation: "Departamento 501",
      commune: "Pocitos",
      region: "Montevideo",
      road: "Bulevar",
      population: "Urbana",
      zipCode: "11300",
      geographicCoordinates: "-34.910, -56.155",
      radio: "Radio de 300 metros",
      complianceSchedule: "Control semanal",
      characteristics: "Edificio frente al mar",
    },
    exclusionArea: {
      street: "Av. 18 de Julio",
      number: "1452",
      additionalInformation: "Clínica San José, pabellón B",
      commune: "Centro",
      region: "Montevideo",
      road: "Avenida principal",
      population: "Urbana",
      zipCode: "11200",
      geographicCoordinates: "-34.906, -56.188",
      radio: "Radio de 100 metros",
      characteristics: "Centro médico",
      paternalSurname: "Silveira",
      motherSurname: "Méndez",
      names: "Dr. Fernando",
      rut: "22334455-6",
      victimEmail: "victima5@correo.uy",
      homeTelephone: "+598 2 400 1234",
      workplaceTelephone: "+598 2 410 5678",
    },
  },
  {
    personalData: {
      fullName: "Ricardo Andrés Flores Guzmán",
      socialName: "",
      paternalSurname: "Flores",
      motherSurname: "Guzmán",
      type_current: "Persona con permiso de trabajo externo",
      gender: "Masculino",
      dateBirth: "1980-11-05",
      maritalStatus: "Casado/a",
      nationality: "Paraguay",
      run: "77889900-1",
      phone: "+595 981 234 567",
      foreigner: false,
    },
    cause: {
      penatype: "Régimen abierto",
      crime: "Abuso de confianza",
      courtAppeals: "Cámara de Apelaciones",
      courtRegion: "Santander",
      court: "Juzgado Penal de la Capital",
      ruc: "556677889",
      rit: "112233445",
      rol: "ROL77889",
    },
    monitoring: {
      crs: "CRS Central",
      areas: "Zona Laboral",
      durationMeasurement: "2 años",
      controlSchedule: "Solo fines de semana",
      effectivePeriod: "1 año",
      requestsFeasibility: "En evaluación",
      judgment: "Firme",
      programmingInstallation: "Parcial",
      installationsDone: "Sí",
      modificationResolution: "En trámite",
      technicalSupports: "Reportes periódicos",
      nonReports: "1 reporte",
      daysControl: "150",
      uninstallations: "No",
    },
    inclusionArea: {
      street: "Calle Palma",
      number: "123",
      additionalInformation: "Edificio comercial",
      commune: "Centro",
      region: "Asunción",
      road: "Calle principal",
      population: "Urbana",
      zipCode: "1100",
      geographicCoordinates: "-25.296, -57.635",
      radio: "Radio de 250 metros",
      complianceSchedule: "Control bisemanal",
      characteristics: "Local en planta baja",
    },
    exclusionArea: {
      street: "Av. Mariscal López",
      number: "3456",
      additionalInformation: "Oficina 203",
      commune: "Villa Morra",
      region: "Asunción",
      road: "Avenida",
      population: "Urbana",
      zipCode: "1126",
      geographicCoordinates: "-25.302, -57.580",
      radio: "Radio de 400 metros",
      characteristics: "Torre ejecutiva",
      paternalSurname: "Benítez",
      motherSurname: "Aguilera",
      names: "Patricia Elizabeth",
      rut: "33445566-7",
      victimEmail: "victima6@correo.py",
      homeTelephone: "+595 21 456 789",
      workplaceTelephone: "+595 21 567 890",
    },
  },
];

export const requesters = [
  {
    fullName: "José Alfredo",
    lastName: "Alfredo",
    middleName: "Gutierrez",
    email: "jose.alfredo@gmail.com",
    phone: "3001234567",
    userType: "Defensor",
    institution: "Tribunal Superior",
    identificationNumber: "AB1234567",
    region: "Bogotá",
    address: "Calle 123 #45-67",
    accessAreas: "Legal",
    registrationDate: "2025-01-10",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Cómo se llama tu madre?",
    observations: "Usuario activo desde enero",
    ruc: "5837488234",
  },
  {
    fullName: "María Fernanda",
    lastName: "López",
    middleName: "González",
    email: "maria.fernanda@gmail.com",
    phone: "3107654321",
    userType: "Particular",
    institution: "Juzgado Primero",
    identificationNumber: "JU9876543",
    region: "Medellín",
    address: "Carrera 45 #12-34",
    accessAreas: "Judicial",
    registrationDate: "2025-01-15",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Cuál es tu color favorito?",
    observations: "Tiene permisos administrativos",
    ruc: "7583478234",
  },
  {
    fullName: "Carlos Rodríguez",
    lastName: "Rodríguez",
    middleName: "Andrés",
    email: "carlos.rodriguez@gmail.com",
    phone: "3058765432",
    userType: "Defensor",
    institution: "Tribunal Distrital",
    identificationNumber: "TR5432109",
    region: "Cali",
    address: "Avenida 5 Norte #10-20",
    accessAreas: "Auditoría",
    registrationDate: "2025-01-18",
    identityVerification: "Pasaporte",
    securityQuestion: "¿En qué ciudad naciste?",
    observations: "Usuario con restricciones de acceso",
    ruc: "45783653",
  },
  {
    fullName: "Luisa Pérez",
    lastName: "Pérez",
    middleName: "María",
    email: "luisa.perez@gmail.com",
    phone: "3201234987",
    userType: "Otros",
    institution: "Corte Suprema",
    identificationNumber: "CO7854123",
    region: "Cartagena",
    address: "Calle del Arzobispado #3-15",
    accessAreas: "Legal y Consultas",
    registrationDate: "2025-01-05",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Cómo se llamaba tu primer colegio?",
    observations: "Tiene múltiples solicitudes activas",
    ruc: "56984737",
  },
  {
    fullName: "Andrés Mejía",
    lastName: "Mejía",
    middleName: "Felipe",
    email: "andres.mejia@gmail.com",
    phone: "3128765432",
    userType: "Particular",
    institution: "Juzgado Segundo",
    identificationNumber: "JU6543219",
    region: "Pereira",
    address: "Calle 14 #8-09",
    accessAreas: "Audiencias",
    registrationDate: "2025-01-12",
    identityVerification: "Licencia profesional",
    securityQuestion: "¿Cuál es tu película favorita?",
    observations: "Usuario de alta prioridad",
    ruc: "89362543",
  },
  {
    fullName: "Camila Ortiz",
    lastName: "Ortiz",
    middleName: "Sofía",
    email: "camila.ortiz@gmail.com",
    phone: "3056781243",
    userType: "Abogado",
    institution: "Empresa de Tecnología XYZ",
    identificationNumber: "INST654321",
    region: "Manizales",
    address: "Carrera 21 #45-67",
    accessAreas: "Técnico",
    registrationDate: "2025-01-03",
    identityVerification: "Certificación técnica",
    securityQuestion: "¿Cuál es tu lugar favorito?",
    observations: "Certificada en sistemas de seguridad",
    ruc: "12381832",
  },
  {
    fullName: "Ricardo López",
    lastName: "López",
    middleName: "Javier",
    email: "ricardo.lopez@gmail.com",
    phone: "3012345678",
    userType: "Defensor",
    institution: "Juzgado Civil Tercero",
    identificationNumber: "AB7890123",
    region: "Villavicencio",
    address: "Diagonal 15 #23-45",
    accessAreas: "Legal y Técnico",
    registrationDate: "2025-01-02",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué marca fue tu primer auto?",
    observations: "Requiere renovación anual de acceso",
    ruc: "39458345",
  },
  {
    fullName: "Tatiana Ramírez",
    lastName: "Ramírez",
    middleName: "Valentina",
    email: "tatiana.ramirez@gmail.com",
    phone: "3194567821",
    userType: "Otros",
    institution: "Tribunal Superior del Atlántico",
    identificationNumber: "TRong147852",
    region: "Barranquilla",
    address: "Calle 50 #20-30",
    accessAreas: "Supervisión",
    registrationDate: "2025-01-08",
    identityVerification: "Tarjeta profesional",
    securityQuestion: "¿Qué sabor de helado prefieres?",
    observations: "Reportes trimestrales requeridos",
    ruc: "57467364",
  },
  {
    fullName: "Paola Gómez",
    lastName: "Gómez",
    middleName: "Alejandra",
    email: "paola.gomez@gmail.com",
    phone: "3114569870",
    userType: "Particular",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
    ruc: "12837467",
  },
  {
    fullName: "Martha Gómez",
    lastName: "Gómez",
    middleName: "Lucía",
    email: "martha.gomez@gmail.com",
    phone: "3114569870",
    userType: "Abogado",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 32 #9-12",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
    ruc: "58342642",
  },
  {
    fullName: "Andres Parrado",
    lastName: "Parrado",
    middleName: "Eduardo",
    email: "andres.parrado@gmail.com",
    phone: "3114569870",
    userType: "Defensor",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Bogotá",
    address: "Carrera 7 #20-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
    ruc: "67477233",
  },
  {
    fullName: "Stive Leguizamon",
    lastName: "Leguizamón",
    middleName: "Manuel",
    email: "stiven@gmail.com",
    phone: "3114569870",
    userType: "Particular",
    institution: "Corte Constitucional",
    identificationNumber: "JU112233",
    region: "Monterry",
    address: "Carrera 8 #25-15",
    accessAreas: "Judicial y Administrativo",
    registrationDate: "2025-01-22",
    identityVerification: "Cédula de ciudadanía",
    securityQuestion: "¿Qué nombre tenía tu primera mascota?",
    observations: "Tiene acceso a casos especiales",
    ruc: "467834672",
  },
];
export const requests = [
  {
    requester_type: "Juez",
    requester_name: "Juan Pérez",
    identification_number: "123456789",
    status: "Sin respuesta",
    situation_type: "Condena",
    request_date: "2023-10-01",
    response_date: "----",
    confirmation: "false",
    hour: "5 horas y 20 minutos",
    requesterType: "Defensor",
    region: "Región Metropolitana",
    tribunalCourt: "Tribunal de Santiago",
    crime: "Robo",
    lastName: "Pérez",
    maternalLastName: "Gómez",
    firstName: "Juan",
    isForeigner: false,
    street: "Calle Falsa",
    number: "123",
    blockApartmentHouse: "Block 4",
    commune: "Santiago",
    highwayRouteKilometer: "Carretera 5",
    populationCondominiumVilla: "Población Los Álamos",
    postalCode: "8320000",
    geographicCoordinates: "-33.4489, -70.6693",
    radius: "5 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona residencial con alta seguridad",
    victimLastName: "López",
    victimMaternalLastName: "Martínez",
    victimFirstName: "Ana",
    victimRut: "98765432-1",
    victimEmail: "ana.lopez@example.com",
    victimPhone: "+56 9 8765 4321",
    victimWorkPhone: "+56 2 2345 6789",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Tech Solutions S.A.",
    identification_number: "987654321",
    situation_type: "Sujeción a control",
    request_date: "2023-10-02",
    response_date: "----",
    status: "Negativo",
    confirmation: "return",
    hour: "13 horas y 15 minutos",
    requesterType: "Abogado",
    region: "Región de Valparaíso",
    tribunalCourt: "Tribunal de Valparaíso",
    crime: "Fraude",
    lastName: "García",
    maternalLastName: "López",
    firstName: "María",
    isForeigner: false,
    street: "Avenida Brasil",
    number: "456",
    blockApartmentHouse: "Departamento 12",
    commune: "Valparaíso",
    highwayRouteKilometer: "Carretera 68",
    populationCondominiumVilla: "Condominio Las Flores",
    postalCode: "2340000",
    geographicCoordinates: "-33.0472, -71.6127",
    radius: "3 km",
    complianceSchedule: "Lunes a Viernes, 9:00 - 17:00",
    sectorCharacteristics: "Zona comercial con alta afluencia",
    victimLastName: "Gómez",
    victimMaternalLastName: "Pérez",
    victimFirstName: "Carlos",
    victimRut: "87654321-0",
    victimEmail: "carlos.gomez@example.com",
    victimPhone: "+56 9 1234 5678",
    victimWorkPhone: "+56 32 8765 4321",
  },
  {
    requester_type: "Abogado",
    requester_name: "María Gómez",
    identification_number: "456789123",
    situation_type: "Condena",
    request_date: "2023-10-03",
    response_date: "2023-10-04",
    status: "No recomendable",
    confirmation: "true",
    hour: "8 horas y 30 minutos",
    requesterType: "Particular",
    region: "Región del Biobío",
    tribunalCourt: "Tribunal de Concepción",
    crime: "Hurto",
    lastName: "Gómez",
    maternalLastName: "Pérez",
    firstName: "María",
    isForeigner: false,
    street: "Calle San Martín",
    number: "789",
    blockApartmentHouse: "Casa 5",
    commune: "Concepción",
    highwayRouteKilometer: "Carretera 160",
    populationCondominiumVilla: "Villa San Pedro",
    postalCode: "4030000",
    geographicCoordinates: "-36.8267, -73.0497",
    radius: "2 km",
    complianceSchedule: "Lunes a Viernes, 10:00 - 16:00",
    sectorCharacteristics: "Zona residencial tranquila",
    victimLastName: "Martínez",
    victimMaternalLastName: "Gómez",
    victimFirstName: "Luis",
    victimRut: "76543210-2",
    victimEmail: "luis.martinez@example.com",
    victimPhone: "+56 9 7654 3210",
    victimWorkPhone: "+56 41 2345 6789",
  },
  {
    requester_type: "Juez",
    requester_name: "Angela Martinez",
    identification_number: "321654987",
    situation_type: "Sujeción a control",
    request_date: "2023-10-04",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "9 horas y 30 minutos",
    requesterType: "Otro",
    region: "Región de Coquimbo",
    tribunalCourt: "Tribunal de La Serena",
    crime: "Violencia doméstica",
    lastName: "López",
    maternalLastName: "Martínez",
    firstName: "Ana",
    isForeigner: false,
    street: "Calle Balmaceda",
    number: "101",
    blockApartmentHouse: "Departamento 3",
    commune: "La Serena",
    highwayRouteKilometer: "Carretera 41",
    populationCondominiumVilla: "Condominio Los Pinos",
    postalCode: "1700000",
    geographicCoordinates: "-29.9027, -71.2519",
    radius: "4 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona residencial con áreas verdes",
    victimLastName: "Gómez",
    victimMaternalLastName: "López",
    victimFirstName: "Sofía",
    victimRut: "65432109-3",
    victimEmail: "sofia.gomez@example.com",
    victimPhone: "+56 9 6543 2109",
    victimWorkPhone: "+56 51 8765 4321",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Carlos Rodríguez",
    identification_number: "789123456",
    situation_type: "Accidente de tránsito",
    request_date: "2023-10-05",
    response_date: "----",
    status: "Positivo",
    confirmation: "return",
    hour: "10 horas",
    requesterType: "Abogado",
    region: "Región de Antofagasta",
    tribunalCourt: "Tribunal de Antofagasta",
    crime: "Conducción bajo la influencia del alcohol",
    lastName: "Rodríguez",
    maternalLastName: "Gómez",
    firstName: "Carlos",
    isForeigner: false,
    street: "Avenida Argentina",
    number: "202",
    blockApartmentHouse: "Block 7",
    commune: "Antofagasta",
    highwayRouteKilometer: "Carretera 1",
    populationCondominiumVilla: "Población Los Olivos",
    postalCode: "1240000",
    geographicCoordinates: "-23.6345, -70.3989",
    radius: "6 km",
    complianceSchedule: "Lunes a Viernes, 7:00 - 19:00",
    sectorCharacteristics: "Zona industrial con tráfico pesado",
    victimLastName: "Martínez",
    victimMaternalLastName: "Rodríguez",
    victimFirstName: "Pedro",
    victimRut: "54321098-4",
    victimEmail: "pedro.martinez@example.com",
    victimPhone: "+56 9 5432 1098",
    victimWorkPhone: "+56 55 1234 5678",
  },
  {
    requester_type: "Abogado",
    requester_name: "Constructora XYZ",
    identification_number: "654987321",
    situation_type: "Condena",
    request_date: "2023-10-06",
    response_date: "2023-10-07",
    status: "Negativo",
    confirmation: "false",
    hour: "4 horas",
    requesterType: "Abogado",
    region: "Región de Los Lagos",
    tribunalCourt: "Tribunal de Puerto Montt",
    crime: "Estafa",
    lastName: "Rodríguez",
    maternalLastName: "Pérez",
    firstName: "Carlos",
    isForeigner: false,
    street: "Calle Los Alerces",
    number: "303",
    blockApartmentHouse: "Casa 8",
    commune: "Puerto Montt",
    highwayRouteKilometer: "Carretera 7",
    populationCondominiumVilla: "Condominio Los Robles",
    postalCode: "5480000",
    geographicCoordinates: "-41.4689, -72.9411",
    radius: "3 km",
    complianceSchedule: "Lunes a Viernes, 9:00 - 17:00",
    sectorCharacteristics: "Zona residencial con vista al mar",
    victimLastName: "Gómez",
    victimMaternalLastName: "Rodríguez",
    victimFirstName: "Laura",
    victimRut: "43210987-5",
    victimEmail: "laura.gomez@example.com",
    victimPhone: "+56 9 4321 0987",
    victimWorkPhone: "+56 65 8765 4321",
  },
  {
    requester_type: "Juez",
    requester_name: "Ana López",
    identification_number: "234567891",
    situation_type: "Otro",
    request_date: "2023-10-07",
    response_date: "2023-10-08",
    status: "No recomendable",
    confirmation: "true",
    hour: "5 horas",
    requesterType: "Defensor",
    region: "Región de Arica y Parinacota",
    tribunalCourt: "Tribunal de Arica",
    crime: "Violencia intrafamiliar",
    lastName: "López",
    maternalLastName: "Gómez",
    firstName: "Ana",
    isForeigner: false,
    street: "Calle 21 de Mayo",
    number: "404",
    blockApartmentHouse: "Departamento 10",
    commune: "Arica",
    highwayRouteKilometer: "Carretera 11",
    populationCondominiumVilla: "Villa Las Palmeras",
    postalCode: "1000000",
    geographicCoordinates: "-18.4783, -70.3126",
    radius: "2 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona urbana con alta densidad poblacional",
    victimLastName: "Martínez",
    victimMaternalLastName: "López",
    victimFirstName: "Pedro",
    victimRut: "32109876-6",
    victimEmail: "pedro.martinez@example.com",
    victimPhone: "+56 9 3210 9876",
    victimWorkPhone: "+56 58 1234 5678",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Jose polo",
    identification_number: "876543219",
    situation_type: "Sujeción a control",
    request_date: "2023-10-08",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "5 horas",
    requesterType: "Particular",
    region: "Región de Magallanes",
    tribunalCourt: "Tribunal de Punta Arenas",
    crime: "Contaminación ambiental",
    lastName: "Gómez",
    maternalLastName: "Martínez",
    firstName: "Luis",
    isForeigner: false,
    street: "Calle Magallanes",
    number: "505",
    blockApartmentHouse: "Block 12",
    commune: "Punta Arenas",
    highwayRouteKilometer: "Carretera 9",
    populationCondominiumVilla: "Condominio Los Cóndores",
    postalCode: "6200000",
    geographicCoordinates: "-53.1638, -70.9171",
    radius: "4 km",
    complianceSchedule: "Lunes a Viernes, 10:00 - 16:00",
    sectorCharacteristics: "Zona industrial con baja contaminación",
    victimLastName: "López",
    victimMaternalLastName: "Gómez",
    victimFirstName: "Sofía",
    victimRut: "21098765-7",
    victimEmail: "sofia.lopez@example.com",
    victimPhone: "+56 9 2109 8765",
    victimWorkPhone: "+56 61 8765 4321",
  },
  {
    requester_type: "Abogado",
    requester_name: "Luis Martínez",
    identification_number: "345678912",
    situation_type: "Condena",
    request_date: "2023-10-09",
    response_date: "2023-10-10",
    status: "Positivo",
    confirmation: "true",
    hour: "6 horas y 10 minutos",
    requesterType: "Abogado",
    region: "Región de O'Higgins",
    tribunalCourt: "Tribunal de Rancagua",
    crime: "Robo con violencia",
    lastName: "Martínez",
    maternalLastName: "Rodríguez",
    firstName: "Luis",
    isForeigner: false,
    street: "Calle Independencia",
    number: "606",
    blockApartmentHouse: "Casa 15",
    commune: "Rancagua",
    highwayRouteKilometer: "Carretera 5",
    populationCondominiumVilla: "Población Los Nogales",
    postalCode: "2820000",
    geographicCoordinates: "-34.1708, -70.7444",
    radius: "5 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona residencial con alta seguridad",
    victimLastName: "Gómez",
    victimMaternalLastName: "Martínez",
    victimFirstName: "Carlos",
    victimRut: "10987654-8",
    victimEmail: "carlos.gomez@example.com",
    victimPhone: "+56 9 1098 7654",
    victimWorkPhone: "+56 72 2345 6789",
  },
  {
    requester_type: "Juez",
    requester_name: "Protección Animal",
    identification_number: "432198765",
    situation_type: "Sujeción a control",
    request_date: "2023-10-10",
    response_date: "2023-10-11",
    status: "Negativo",
    confirmation: "false",
    hour: "3 horas",
    requesterType: "Otro",
    region: "Región de Tarapacá",
    tribunalCourt: "Tribunal de Iquique",
    crime: "Maltrato animal",
    lastName: "López",
    maternalLastName: "Gómez",
    firstName: "Ana",
    isForeigner: false,
    street: "Calle Baquedano",
    number: "707",
    blockApartmentHouse: "Departamento 20",
    commune: "Iquique",
    highwayRouteKilometer: "Carretera 16",
    populationCondominiumVilla: "Condominio Los Flamencos",
    postalCode: "1100000",
    geographicCoordinates: "-20.2133, -70.1503",
    radius: "3 km",
    complianceSchedule: "Lunes a Viernes, 9:00 - 17:00",
    sectorCharacteristics: "Zona turística con áreas verdes",
    victimLastName: "Martínez",
    victimMaternalLastName: "López",
    victimFirstName: "Pedro",
    victimRut: "09876543-9",
    victimEmail: "pedro.martinez@example.com",
    victimPhone: "+56 9 0987 6543",
    victimWorkPhone: "+56 57 8765 4321",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Sofía Ramírez",
    identification_number: "567891234",
    situation_type: "Condena",
    request_date: "2023-10-11",
    response_date: "2023-10-12",
    status: "No recomendable",
    confirmation: "false",
    hour: "7 horas 10 minutos",
    requesterType: "Defensor",
    region: "Región de Los Ríos",
    tribunalCourt: "Tribunal de Valdivia",
    crime: "Robo en lugar no habitado",
    lastName: "Ramírez",
    maternalLastName: "Gómez",
    firstName: "Sofía",
    isForeigner: false,
    street: "Calle Picarte",
    number: "808",
    blockApartmentHouse: "Casa 25",
    commune: "Valdivia",
    highwayRouteKilometer: "Carretera 202",
    populationCondominiumVilla: "Condominio Los Laureles",
    postalCode: "5090000",
    geographicCoordinates: "-39.8142, -73.2459",
    radius: "4 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona residencial con áreas verdes",
    victimLastName: "Gómez",
    victimMaternalLastName: "Ramírez",
    victimFirstName: "Laura",
    victimRut: "98765432-0",
    victimEmail: "laura.gomez@example.com",
    victimPhone: "+56 9 9876 5432",
    victimWorkPhone: "+56 63 1234 5678",
  },
  {
    requester_type: "Abogado",
    requester_name: "Mike Alfonso",
    identification_number: "219876543",
    situation_type: "Otro",
    request_date: "2023-10-12",
    response_date: "----",
    status: "Sin respuesta",
    confirmation: "false",
    hour: "26 horas 25 minutos",
    requesterType: "Abogado",
    region: "Región de Atacama",
    tribunalCourt: "Tribunal de Copiapó",
    crime: "Accidente de tránsito",
    lastName: "Gómez",
    maternalLastName: "Martínez",
    firstName: "Carlos",
    isForeigner: false,
    street: "Calle Atacama",
    number: "909",
    blockApartmentHouse: "Departamento 30",
    commune: "Copiapó",
    highwayRouteKilometer: "Carretera 5",
    populationCondominiumVilla: "Población Los Olivos",
    postalCode: "1530000",
    geographicCoordinates: "-27.3668, -70.3322",
    radius: "5 km",
    complianceSchedule: "Lunes a Viernes, 9:00 - 17:00",
    sectorCharacteristics: "Zona urbana con tráfico moderado",
    victimLastName: "Martínez",
    victimMaternalLastName: "Gómez",
    victimFirstName: "Pedro",
    victimRut: "87654321-1",
    victimEmail: "pedro.martinez@example.com",
    victimPhone: "+56 9 8765 4321",
    victimWorkPhone: "+56 52 2345 6789",
  },
  {
    requester_type: "Juez",
    requester_name: "Pedro Sánchez",
    identification_number: "678912345",
    situation_type: "Sujeción a control",
    request_date: "2023-10-13",
    response_date: "2023-10-14",
    status: "Positivo",
    confirmation: "true",
    hour: "10 horas",
    requesterType: "Particular",
    region: "Región de Ñuble",
    tribunalCourt: "Tribunal de Chillán",
    crime: "Estafa financiera",
    lastName: "Sánchez",
    maternalLastName: "López",
    firstName: "Pedro",
    isForeigner: false,
    street: "Calle Arauco",
    number: "1010",
    blockApartmentHouse: "Casa 35",
    commune: "Chillán",
    highwayRouteKilometer: "Carretera 152",
    populationCondominiumVilla: "Condominio Los Cerezos",
    postalCode: "3780000",
    geographicCoordinates: "-36.6066, -72.1034",
    radius: "3 km",
    complianceSchedule: "Lunes a Viernes, 10:00 - 16:00",
    sectorCharacteristics: "Zona residencial con comercios locales",
    victimLastName: "López",
    victimMaternalLastName: "Sánchez",
    victimFirstName: "Ana",
    victimRut: "76543210-2",
    victimEmail: "ana.lopez@example.com",
    victimPhone: "+56 9 7654 3210",
    victimWorkPhone: "+56 42 8765 4321",
  },
  {
    requester_type: "Tribunal",
    requester_name: "Educación para Todos",
    identification_number: "543219876",
    situation_type: "Otro",
    request_date: "2023-10-14",
    response_date: "2023-10-15",
    status: "Negativo",
    confirmation: "true",
    hour: "11 horas",
    requesterType: "Otro",
    region: "Región de Aysén",
    tribunalCourt: "Tribunal de Coyhaique",
    crime: "Fraude educativo",
    lastName: "Gómez",
    maternalLastName: "Martínez",
    firstName: "Laura",
    isForeigner: false,
    street: "Calle Simpson",
    number: "1111",
    blockApartmentHouse: "Departamento 40",
    commune: "Coyhaique",
    highwayRouteKilometer: "Carretera 7",
    populationCondominiumVilla: "Condominio Los Coigües",
    postalCode: "5950000",
    geographicCoordinates: "-45.5752, -72.0662",
    radius: "2 km",
    complianceSchedule: "Lunes a Viernes, 8:00 - 18:00",
    sectorCharacteristics: "Zona rural con baja densidad poblacional",
    victimLastName: "Martínez",
    victimMaternalLastName: "Gómez",
    victimFirstName: "Carlos",
    victimRut: "65432109-3",
    victimEmail: "carlos.martinez@example.com",
    victimPhone: "+56 9 6543 2109",
    victimWorkPhone: "+56 67 1234 5678",
  },
  {
    requester_type: "Abogado",
    requester_name: "Laura Torres",
    identification_number: "789123456",
    situation_type: "Condena",
    request_date: "2023-10-15",
    response_date: "----",
    status: "No recomendable",
    confirmation: "return",
    hour: "4 horas",
    requesterType: "Abogado",
    region: "Región de La Araucanía",
    tribunalCourt: "Tribunal de Temuco",
    crime: "Violencia intrafamiliar",
    lastName: "Torres",
    maternalLastName: "Gómez",
    firstName: "Laura",
    isForeigner: false,
    street: "Calle Manuel Montt",
    number: "1212",
    blockApartmentHouse: "Casa 45",
    commune: "Temuco",
    highwayRouteKilometer: "Carretera 5",
    populationCondominiumVilla: "Población Los Robles",
    postalCode: "4780000",
    geographicCoordinates: "-38.7359, -72.5907",
    radius: "4 km",
    complianceSchedule: "Lunes a Viernes, 9:00 - 17:00",
    sectorCharacteristics: "Zona urbana con alta densidad poblacional",
    victimLastName: "Gómez",
    victimMaternalLastName: "Torres",
    victimFirstName: "Pedro",
    victimRut: "54321098-4",
    victimEmail: "pedro.gomez@example.com",
    victimPhone: "+56 9 5432 1098",
    victimWorkPhone: "+56 45 8765 4321",
  },
];

export const workLoad = [
  { id: 1, name: "Ana García", openCases: 5, closedCases: 15, laborLoad: 75 },
  {
    id: 2,
    name: "Luis Martínez",
    openCases: 3,
    closedCases: 10,
    laborLoad: 60,
  },
  { id: 3, name: "María López", openCases: 7, closedCases: 20, laborLoad: 85 },
  {
    id: 4,
    name: "Carlos Sánchez",
    openCases: 2,
    closedCases: 8,
    laborLoad: 50,
  },
  {
    id: 5,
    name: "Sofía Ramírez",
    openCases: 6,
    closedCases: 18,
    laborLoad: 80,
  },
  {
    id: 6,
    name: "Jorge Fernández",
    openCases: 4,
    closedCases: 12,
    laborLoad: 70,
  },
  { id: 7, name: "Elena Torres", openCases: 1, closedCases: 5, laborLoad: 40 },
  { id: 8, name: "Miguel Díaz", openCases: 8, closedCases: 22, laborLoad: 90 },
  { id: 9, name: "Lucía Morales", openCases: 3, closedCases: 9, laborLoad: 55 },
  {
    id: 10,
    name: "Pedro Ortega",
    openCases: 6,
    closedCases: 16,
    laborLoad: 78,
  },
  { id: 11, name: "Carmen Ruiz", openCases: 2, closedCases: 7, laborLoad: 45 },
  {
    id: 12,
    name: "Diego Castro",
    openCases: 5,
    closedCases: 14,
    laborLoad: 72,
  },
  {
    id: 13,
    name: "Paula Jiménez",
    openCases: 4,
    closedCases: 11,
    laborLoad: 65,
  },
  {
    id: 14,
    name: "Javier Navarro",
    openCases: 9,
    closedCases: 25,
    laborLoad: 95,
  },
  { id: 15, name: "Isabel Vega", openCases: 3, closedCases: 10, laborLoad: 58 },
];

export const obligations = [
  {
    contractualObligation: "Pago de renta mensual",
    fileName: "Contrato_001.pdf",
    status: "Activo",
    observations: "Sin retrasos en pagos",
  },
  {
    contractualObligation: "Entrega de informe trimestral",
    fileName: "Informe_Q1_2025.docx",
    status: "Pendiente",
    observations: "Fecha límite: 15 de abril",
  },
  {
    contractualObligation: "Mantenimiento de equipos",
    fileName: "Plan_Mantenimiento_2025.xlsx",
    status: "En progreso",
    observations: "Revisión programada para mayo",
  },
  {
    contractualObligation: "Capacitación anual de personal",
    fileName: "Capacitacion_2025.pdf",
    status: "Completado",
    observations: "Finalizó el 20 de marzo",
  },
  {
    contractualObligation: "Renovación de licencia",
    fileName: "Licencia_2025.txt",
    status: "Pendiente",
    observations: "Vence el 30 de junio",
  },
  {
    contractualObligation: "Auditoría interna",
    fileName: "Auditoria_001.pdf",
    status: "En progreso",
    observations: "Inicio el 1 de abril",
  },
  {
    contractualObligation: "Pago a proveedores",
    fileName: "Factura_032.pdf",
    status: "Activo",
    observations: "Monto: $15,000 MXN",
  },
  {
    contractualObligation: "Entrega de productos",
    fileName: "Orden_Entrega_005.docx",
    status: "Completado",
    observations: "Entregado el 2 de abril",
  },
  {
    contractualObligation: "Revisión de contratos",
    fileName: "Contrato_Revision_2025.pdf",
    status: "Pendiente",
    observations: "Programada para mayo",
  },
  {
    contractualObligation: "Actualización de software",
    fileName: "Update_Log.txt",
    status: "En progreso",
    observations: "Versión 2.1 en pruebas",
  },
  {
    contractualObligation: "Reporte de ventas",
    fileName: "Ventas_Marzo_2025.xlsx",
    status: "Completado",
    observations: "Enviado el 31 de marzo",
  },
  {
    contractualObligation: "Seguro de activos",
    fileName: "Poliza_2025.pdf",
    status: "Activo",
    observations: "Vigente hasta diciembre",
  },
  {
    contractualObligation: "Evaluación de desempeño",
    fileName: "Evaluacion_001.docx",
    status: "Pendiente",
    observations: "Programada para abril",
  },
  {
    contractualObligation: "Cumplimiento normativo",
    fileName: "Normas_2025.pdf",
    status: "En progreso",
    observations: "Revisión en curso",
  },
  {
    contractualObligation: "Pago de impuestos",
    fileName: "Declaracion_2025.pdf",
    status: "Pendiente",
    observations: "Fecha límite: 30 de abril",
  },
];
